services:
  auth_service:
    build:
      context: .
      dockerfile: ./backend/auth_service/Dockerfile
    env_file:
      - ./backend/auth_service/.env_example
    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  user_service:
    build:
      context: .
      dockerfile: ./backend/user_service/Dockerfile
    env_file:
      - ./backend/user_service/.env_example
    ports:
      - "8002:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  goal_service:
    build:
      context: .
      dockerfile: ./backend/goal_service/Dockerfile
    env_file:
      - ./backend/goal_service/.env_example
    ports:
      - "8003:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  task_service:
    build:
      context: .
      dockerfile: ./backend/task_service/Dockerfile
    env_file:
      - ./backend/task_service/.env_example
    ports:
      - "8004:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  notification_service:
    build:
      context: .
      dockerfile: ./backend/notification_service/Dockerfile
    env_file:
      - ./backend/notification_service/.env_example
    ports:
      - "8005:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  calendar_service:
    build:
      context: .
      dockerfile: ./backend/calendar_service/Dockerfile
    env_file:
      - ./backend/calendar_service/.env_example
    ports:
      - "8006:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  proxy_service:
    build:
      context: .
      dockerfile: ./backend/proxy_service/Dockerfile
    env_file:
      - ./backend/proxy_service/.env_example
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
